[package]
name = "ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.183"
anyhow = "1.0.75"
futures = "0.3.28"
async-trait = "0.1.73"

paladin = { path = "../../../paladin" }
